### ISSUE TITLE
Read Time Out

### ISSUE THREAD

**Issue by VadneyK** [Kylin-Network/kylin-collator#20]
Hello, I am following the readme on this page to try and run a sample node, but am having the issue below. Do I need to go and put down some firewall that is preventing read or is the kylin nodes just down for now?

------
kentarovadney@Kentaros-MacBook-Air desktop % git clone https://github.com/Kylin-Network/kylin-collator.git
Cloning into 'kylin-collator'...
remote: Enumerating objects: 1290, done.
remote: Counting objects: 100% (391/391), done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 1290 (delta 247), reused 291 (delta 180), pack-reused 899
Receiving objects: 100% (1290/1290), 13.43 MiB | 7.93 MiB/s, done.
Resolving deltas: 100% (782/782), done.
kentarovadney@Kentaros-MacBook-Air desktop % docker-compose -f scripts/docker-compose.yml up -d

ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './scripts/docker-compose.yml'
kentarovadney@Kentaros-MacBook-Air desktop % cd kylin-collator 
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker-compose -f scripts/docker-compose.yml up -d

Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "scripts_default" with the default driver
Creating volume "scripts_es-data" with local driver
Pulling launch (kylinnetwork/kylin-collator:main)...
main: Pulling from kylinnetwork/kylin-collator
c549ccf8d472: Already exists
fa10be5839a0: Pull complete
66dbd750e406: Pull complete
2febc79bcdc5: Pull complete
a12c53ab8ca8: Pull complete
0b8530bf9dd0: Pull complete
38ea596173ff: Pull complete
99cd62cf95fd: Pull complete
616892fb9052: Pull complete
94f15ef8b1c4: Pull complete
b5a87f31cab2: Pull complete
6a4abbb3aecf: Pull complete
214d89da15d6: Pull complete
b57c9db59399: Pull complete
09aa1893895f: Pull complete
a160ef49eba4: Pull complete
ae7190925b3b: Pull complete
75ee73a4f420: Pull complete
1493e5cda285: Pull complete
381cb12ab794: Pull complete
8477fc8d81a4: Pull complete
430c773b1258: Pull complete
08744b4ba22e: Pull complete
ed0931622051: Pull complete
Digest: sha256:cbceba912d71b87308dcafe297d5491c6c1ecaabbc39c19073078fbdcd09178a
Status: Downloaded newer image for kylinnetwork/kylin-collator:main
Pulling kylin-es (docker.elastic.co/elasticsearch/elasticsearch:7.8.1)...
7.8.1: Pulling from elasticsearch/elasticsearch
3843fbcd0044: Pull complete
5cce5f3bc8c0: Pull complete
a9f2b7648bda: Pull complete
c130744d180d: Pull complete
15fa2f725a44: Pull complete
34afbf15f401: Pull complete
29b725957195: Pull complete
1cf49b60819e: Pull complete
c5e42506f6dc: Pull complete
Digest: sha256:54b6af874560621c7791a0845359f2013b42592b18f38857b22fd18246f8afd1
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:7.8.1
Pulling kylin-kibana (docker.elastic.co/kibana/kibana:7.8.1)...
7.8.1: Pulling from kibana/kibana
86dbb57a3083: Pull complete
fe2e912251c2: Pull complete
565c9b40a27d: Pull complete
298ba39da80b: Pull complete
f6057c975a14: Pull complete
75ebf1658d48: Pull complete
1b7b5f7489f8: Pull complete
61705f5cf851: Pull complete
0d40651b1f3c: Pull complete
9d19e28c4d6c: Pull complete
ed47f904cd11: Pull complete
Digest: sha256:2a9cc31f8836d857f816c693c92c3bcacf0bd3060ac4d3183374e68e38540c2c
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:7.8.1
Creating frontend     ... done
Creating kylin-es ... done
Creating launch   ... 
Creating kylin-kibana ... done
Creating init-es-index         ... done
Creating init-kibana-dashboard ... done

ERROR: for launch  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for launch  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker ps

CONTAINER ID   IMAGE                                                 COMMAND                  CREATED         STATUS         PORTS                                                                                 NAMES
9030fea43e76   docker.elastic.co/kibana/kibana:7.8.1                 "/usr/local/bin/dumb…"   6 minutes ago   Up 6 minutes   0.0.0.0:5601->5601/tcp, :::5601->5601/tcp                                             kylin-kibana
6c9ac86cbb11   kylinnetwork/kylin-collator:main                      "bash -c 'cd /apps &…"   6 minutes ago   Up 6 minutes   8080/tcp, 9933-9960/tcp, 0.0.0.0:3001->3001/tcp, :::3001->3001/tcp, 30330-30345/tcp   frontend
ee1a637e69c8   docker.elastic.co/elasticsearch/elasticsearch:7.8.1   "/tini -- /usr/local…"   6 minutes ago   Up 6 minutes   9200/tcp, 9300/tcp                                                                    kylin-es
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker logs launch
/usr/bin/rm: cannot remove '*.log': No such file or directory

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
/usr/bin/bash: line 1:    12 Trace/breakpoint trap   polkadot-launch kylinPolkadotLaunchConfig.json
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker logs frontend

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator %  
zsh: command not found:  
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker-compose -f scripts/docker-compose.yml up -d

Docker Compose is now in the Docker CLI, try `docker compose up`

frontend is up-to-date
kylin-es is up-to-date
Starting launch ... 
Starting launch                ... done
Starting init-es-index         ... done
Starting init-kibana-dashboard ... done
Creating insert-ocw            ... done
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % 
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker logs launch                                
/usr/bin/rm: cannot remove '*.log': No such file or directory

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
/usr/bin/bash: line 1:    12 Trace/breakpoint trap   polkadot-launch kylinPolkadotLaunchConfig.json
/usr/bin/rm: cannot remove '*.log': No such file or directory

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
/usr/bin/bash: line 1:    12 Trace/breakpoint trap   polkadot-launch kylinPolkadotLaunchConfig.json
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker logs frontend                              

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
kentarovadney@Kentaros-MacBook-Air kylin-collator % >....                                                                             
/usr/bin/rm: cannot remove '*.log': No such file or directory

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
/usr/bin/bash: line 1:    12 Trace/breakpoint trap   polkadot-launch kylinPolkadotLaunchConfig.json
/usr/bin/rm: cannot remove '*.log': No such file or directory

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
/usr/bin/bash: line 1:    12 Trace/breakpoint trap   polkadot-launch kylinPolkadotLaunchConfig.json
kentarovadney@Kentaros-MacBook-Air kylin-collator % docker logs frontend                              

#
# Fatal process OOM in Failed to reserve virtual memory for CodeRange
#

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
kentarovadney@Kentaros-MacBook-Air kylin-collator %

**Comment by loganbonsignore** [comment]
Thanks for your question - try extending the `COMPOSE_HTTP_TIMEOUT` env variable with:

`COMPOSE_HTTP_TIMEOUT=200 docker-compose -f scripts/docker-compose.yml up -d`

It is also advisable to clone the repo with the --recursive flag, `git clone --recursive https://github.com/Kylin-Network/kylin-collator.git`

**Comment by loganbonsignore** [comment]
As mentioned in our [telegram chat](https://t.me/kylin_technical/3875), if the issue persists you may need to increase both the ram and storage for your docker set-up.
