### ISSUE TITLE
tokio-runtime-worker panicked

### ISSUE THREAD

**Issue by jph4157** [Kylin-Network/kylin-collator#39]
Version: 2.0.0-6d5f095-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   5: std::panicking::begin_panic_fmt
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:460:5
   6: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   7: <sc_client_db::BlockchainDb<Block> as sp_blockchain::backend::Backend<Block>>::justifications
   8: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::client::BlockBackend<Block>>::justifications
   9: sc_network::block_request_handler::BlockRequestHandler<B>::handle_request
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: tokio::runtime::task::core::CoreStage<T>::poll
  15: tokio::runtime::task::harness::Harness<T,S>::poll
  16: tokio::runtime::thread_pool::worker::Context::run_task
  17: tokio::runtime::thread_pool::worker::Context::run
  18: tokio::macros::scoped_tls::ScopedKey<T>::set
  19: tokio::runtime::thread_pool::worker::run
  20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  21: tokio::runtime::task::core::CoreStage<T>::poll
  22: tokio::runtime::task::harness::Harness<T,S>::poll
  23: tokio::runtime::blocking::pool::Inner::run
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys/unix/thread.rs:106:17
  27: start_thread
  28: clone

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "IO error: While pread offset 17888251 len 10173: cumulus_parachain/kylin-collator-1/polkadot/chains/westend2/db/full/096301.sst: Input/output error" } }', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/632b323/primitives/database/src/kvdb.rs:29

**Comment by loganbonsignore** [comment]
Hello, please provide more information for us to work with. Are you launching with Docker or building from source? Locally or an external relay chain? We are happy to help when we know more about this specific case.

**Comment by sylvaincormier** [comment]
Closing this due to no feedback
